# Site settings
title: Uijin Jung
description: Uijin Jung's github blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Uijin Jeong
user_description: I have interest in reinforcement learning, especially in the real-world. Also undergoing studying deep-learning computer vision, and Want to study nlp someday either.
user_title: Ai developer
email: jin.Prelude@gmail.com
twitter_username: Null
github_username:  jinPrelude
gplus_username:  Null

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
